PORTNAME=	aws-ssm
DISTVERSION=	1.2.339.0
CATEGORIES=	security

MAINTAINER=	bryan@frimin.fr
COMMENT=	Start and end sessions to your managed instances

LICENSE=	APACHE20

USES=	go:modules

USE_GITHUB=	yes
GH_ACCOUNT=	aws
GH_PROJECT=	session-manager-plugin

.include <bsd.port.mk>
